# Generated by Django 4.2.7 on 2026-02-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdiscount',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Сумма скидки'),
        ),
    ]
