# Generated by Django 4.2.7 on 2026-02-24 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ['date'], 'verbose_name': 'Концерт', 'verbose_name_plural': 'Концерты'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.AlterField(
            model_name='concert',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='country',
            field=models.CharField(default='Россия', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена билета'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='sold_tickets',
            field=models.IntegerField(default=0, verbose_name='Продано билетов'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Предстоящий'), ('soldout', 'Все билеты проданы'), ('cancelled', 'Отменен'), ('completed', 'Прошел')], default='upcoming', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='ticket_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL покупки билетов'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='total_tickets',
            field=models.IntegerField(default=100, verbose_name='Всего билетов'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='venue',
            field=models.CharField(max_length=200, verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='concerts.concert', verbose_name='Концерт'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_used_for_discount',
            field=models.BooleanField(default=False, verbose_name='Использован для скидки'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена покупки'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер билета'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
    ]
