# Generated by Django 4.2.7 on 2026-02-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_alter_concert_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='city',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(db_index=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='sold_tickets',
            field=models.PositiveIntegerField(default=0, verbose_name='Продано билетов'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='total_tickets',
            field=models.PositiveIntegerField(default=100, verbose_name='Всего билетов'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='venue',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Номер билета'),
        ),
        migrations.AddIndex(
            model_name='concert',
            index=models.Index(fields=['status', 'date'], name='concerts_co_status_581698_idx'),
        ),
    ]
