# Generated by Django 4.2.7 on 2026-03-16 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concerts', '0003_alter_concert_city_alter_concert_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='attendees',
            field=models.ManyToManyField(related_name='attended_concerts', through='concerts.Ticket', to=settings.AUTH_USER_MODEL),
        ),
    ]
