# Generated by Django 4.2.7 on 2026-02-24 05:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('clothing', 'Одежда'), ('accessories', 'Аксессуары'), ('vinyl', 'Винил'), ('cd', 'CD'), ('other', 'Другое')], default='clothing', max_length=20, verbose_name='Категория')),
                ('main_image', models.URLField(blank=True, max_length=500, verbose_name='Главное фото')),
                ('artist', models.CharField(blank=True, max_length=200, verbose_name='Исполнитель')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата релиза')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL изображения')),
                ('display_order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Главное')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='merch.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('display_name', models.CharField(max_length=200, verbose_name='Отображаемое название')),
                ('attributes', models.JSONField(default=dict, help_text='{"size": "M", "color": "Black", "material": "cotton"}', verbose_name='Характеристики')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток')),
                ('image', models.URLField(blank=True, max_length=500, verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='merch.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товарная позиция (SKU)',
                'verbose_name_plural': 'Товарные позиции (SKU)',
                'unique_together': {('product', 'attributes')},
            },
        ),
    ]
