# Generated by Django 4.2.7 on 2026-02-23 07:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('clothing', 'Одежда'), ('accessories', 'Аксессуары'), ('vinyl', 'Винил'), ('cd', 'CD'), ('other', 'Другое')], default='clothing', max_length=20)),
                ('main_image', models.URLField(blank=True, max_length=500)),
                ('stock_total', models.IntegerField(default=0, help_text='Общий остаток на складе')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500)),
                ('display_order', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('merch_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='merch.merchitem')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='MerchVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(blank=True, help_text='S, M, L, XL или пусто для аксессуаров', max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('merch_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='merch.merchitem')),
            ],
            options={
                'unique_together': {('merch_item', 'size', 'color')},
            },
        ),
    ]
