# Generated by Django 4.2.7 on 2026-02-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['display_order'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['product__name', 'price'], 'verbose_name': 'Товарная позиция (SKU)', 'verbose_name_plural': 'Товарные позиции (SKU)'},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='display_name',
            field=models.CharField(editable=False, max_length=200, verbose_name='Отображаемое название'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_code',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Артикул'),
        ),
    ]
