# Generated by Django 4.2.7 on 2026-02-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_alter_productimage_options_alter_sku_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='image',
        ),
    ]
