# Generated by Django 4.2.7 on 2026-03-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_remove_productimage_is_primary_remove_sku_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='', upload_to='products/%Y/%m/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
