# Generated by Django 4.2.7 on 2026-02-24 05:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_alter_concert_options_alter_ticket_options_and_more'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Промо-код', 'verbose_name_plural': 'Промо-коды'},
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Промо-код'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_percent',
            field=models.IntegerField(default=15, help_text='Процент скидки', verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_code', to='concerts.ticket', verbose_name='Билет'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='valid_until',
            field=models.DateField(verbose_name='Действителен до'),
        ),
    ]
