# Generated by Django 4.2.7 on 2026-02-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_alter_discountcode_options_alter_discountcode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='discount_percent',
            field=models.PositiveIntegerField(default=15, verbose_name='Процент скидки'),
        ),
    ]
