# Generated by Django 4.2.7 on 2026-02-23 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(default='ẃ1lq', max_length=100)),
                ('release_date', models.DateField()),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('album', 'Album'), ('single', 'Single'), ('ep', 'EP')], default='single', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('duration_seconds', models.IntegerField(help_text='Длина трека в секундах')),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('track_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.release')),
            ],
            options={
                'ordering': ['track_number'],
                'unique_together': {('release', 'track_number')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='music.release')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'release')},
            },
        ),
    ]
