# Generated by Django 4.2.7 on 2026-02-24 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные релизы'},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-release_date'], 'verbose_name': 'Релиз', 'verbose_name_plural': 'Релизы'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['track_number'], 'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='music.release', verbose_name='Релиз'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_releases', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='release',
            name='artist',
            field=models.CharField(default='ẃ1lq', max_length=100, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='release',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL обложки'),
        ),
        migrations.AlterField(
            model_name='release',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='release',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='release',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='В рекомендациях'),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateField(verbose_name='Дата релиза'),
        ),
        migrations.AlterField(
            model_name='release',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='release',
            name='type',
            field=models.CharField(choices=[('album', 'Альбом'), ('single', 'Сингл'), ('ep', 'EP')], default='single', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL аудио'),
        ),
        migrations.AlterField(
            model_name='track',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration_seconds',
            field=models.IntegerField(help_text='Длина трека в секундах', verbose_name='Длительность (сек)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='track',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.release', verbose_name='Релиз'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_number',
            field=models.IntegerField(verbose_name='Номер трека'),
        ),
    ]
