# Generated by Django 4.2.7 on 2026-02-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_favorite_options_alter_release_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-added_at'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные релизы'},
        ),
        migrations.AlterField(
            model_name='release',
            name='artist',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='release',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='release',
            name='type',
            field=models.CharField(choices=[('album', 'Альбом'), ('single', 'Сингл'), ('ep', 'EP'), ('live', 'Концертный альбом'), ('compilation', 'Сборник')], default='single', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration_seconds',
            field=models.IntegerField(verbose_name='Длительность (секунд)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_number',
            field=models.PositiveIntegerField(verbose_name='Номер трека'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['artist', 'release_date'], name='music_relea_artist_745df9_idx'),
        ),
    ]
