# Generated by Django 4.2.7 on 2026-03-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_favorite_options_alter_release_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='cover_url',
        ),
        migrations.RemoveField(
            model_name='track',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='release',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='track',
            name='file',
            field=models.FileField(default=' ', upload_to='music/', verbose_name='Аудио файл'),
            preserve_default=False,
        ),
    ]
